#!/bin/sh
set -e

echo "">.env;
export ASSETS_VERSION=`date +'%s'`
bash -c "declare -p" | grep -Ev 'BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID' > /container.env
su -p www-data -s /bin/bash -c "composer install --prefer-dist --no-interaction --optimize-autoloader"
su -p www-data -s /bin/bash -c "php bin/console doctrine:migrations:migrate --no-interaction --no-debug"
su -p  www-data -s /bin/bash -c "php bin/console cache:warmup --env=prod --no-debug"
su -p  www-data -s /bin/bash -c "php bin/console --env=prod stat:import:ieee"
rm -rf web/app_dev.php
rm -rf web/config.php

service nginx start
cron &
# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"
