#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi
echo "">.env;
su -p -l www-data -s /bin/bash -c "composer --prefer-dist --no-interaction --optimize-autoloader"
su -p -l www-data -s /bin/bash -c "php bin/console doctrine:migrations:migrate --no-interaction --no-debug"
rm -rf web/app_dev.php
rm -rf web/config.php
service nginx start
exec "$@"
